source 'https://rubygems.org'

gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'devise'
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'active_admin_editor'
gem 'acts-as-taggable-on'
gem 'pg_search'
